---
- hosts: all
  tasks:
  - name: Install baseline dependencies
    apt:
      name: software-properties-common
      state: present
      update_cache: yes
    become: yes

  - name: Add GlusterFS apt key
    apt_key:
      url: https://download.gluster.org/pub/gluster/glusterfs/7/rsa.pub
      state: present
    become: yes

  - name: Add GlusterFS PPA
    apt_repository:
      repo: ppa:gluster/glusterfs-7
      state: present
      update_cache: yes
    become: yes

  - name: Install GlusterFS Server
    apt:
      name: glusterfs-server
      state: present
    become: yes

  - name: Enable and start GlusterFS Server
    service:
      name: glusterd
      enabled: yes
      state: started
    become: yes

- hosts: vol1
  tasks:
  - name: Probe first peer
    shell: gluster peer probe {{ groups['vol2'][0] }}
    become: yes
  - name: Probe second peer
    shell: gluster peer probe {{ groups['vol3'][0] }}
    become: yes

- hosts: vol2
  tasks:
  - name: Close the loop
    shell: gluster peer probe {{ groups['vol1'][0] }}
    become: yes

- hosts: all
  tasks:
  - name: Create data directory
    file:
      state: directory
      path: /vroot/data/brick
    become: yes

- hosts: vol1
  tasks:
  - name: Create the Gluster volume
    command: gluster volume create gv0 replica 3 {{ groups['vol1'][0] }}:/vroot/data/brick {{ groups['vol2'][0] }}:/vroot/data/brick {{ groups['vol3'][0] }}:/vroot/data/brick force
    become: yes

  - name: Start the Gluster volume
    command: gluster volume start gv0
    become: yes
